add backend lesson
SkylabCoders/skylab-bootcamp-202104-madrid pull request #229
Opened 2021-05-19 18:34 UTC by SaraCubero

2021-05-19 18:36 UTC, Adanzar approved these changes

2021-05-20 07:16 UTC, gilbecao commented on challenges/sara/curso/week-6/api/rest-demo-2/controllers/RickController.js
> +  postHero: (req, res) => {
Change function name

2021-05-20 07:16 UTC, gilbecao commented on challenges/sara/curso/week-6/api/rest-demo-2/controllers/RickController.js
> +  postHero: (req, res) => {
Change every reference to heroes

2021-05-20 07:18 UTC, gilbecao commented on challenges/sara/curso/week-6/api/rest-demo-2/routes/heroRoutes.js
> +  heroRoutes
Move to a new file and call from index

2021-05-20 07:35 UTC, gilbecao requested changes
Review comments

2021-05-20 08:04 UTC, gilbecao approved these changes

2021-05-20 08:04 UTC, merged